//Depart List
export const LOAD_DEPARTS = 'LOAD_DEPARTS';
export const LOAD_DEPARTS_SUCCESS = 'LOAD_DEPARTS_SUCCESS';
export const LOAD_DEPARTS_FAILURE = 'LOAD_DEPARTs_FAILURE';

//Depart New, Save, Update
export const SAVE_DEPART = 'SAVE_DEPART';
export const SAVE_DEPART_SUCCESS = 'SAVE_DEPARTS_SUCCESS';
export const SAVE_DEPART_FAILURE = 'SAVE_DEPART_FAILURE';

//Depart Delete
export const DELETE_DEPART = 'DELETE_DEPART';
export const DELETE_DEPART_SUCCESS = 'DELETE_DEPART_SUCCESS';
export const DELETE_DEPART_FAILURE = 'DELETE_FACULTY_FAILURE';

//Get 1 Row
export const LOAD_DEPART = 'LOAD_DEPART';
export const LOAD_DEPART_SUCCESS = 'LOAD_DEPART_SUCCESS';
export const LOAD_DEPART_FAILURE = 'LOAD_DEPART_FAILURE';
export const RESET_DEPART = 'RESET_DEPART';