//Faculty list
export const LOAD_FACULTYS = 'LOAD_FACULTYS';
export const LOAD_FACULTYS_SUCCESS = 'LOAD_FACULTYS_SUCCESS';
export const LOAD_FACULTYS_FAILURE = 'LOAD_FACULTYS_FAILURE';

//Faculty New, Save, Update
export const SAVE_FACULTY = 'SAVE_FACULTY';
export const SAVE_FACULTY_SUCCESS = 'SAVE_FACULTYS_SUCCESS';
export const SAVE_FACULTY_FAILURE = 'SAVE_FACULTY_FAILURE';

//Faculty Delete
export const DELETE_FACULTY = 'DELETE_FACULTY';
export const DELETE_FACULTY_SUCCESS = 'DELETE_FACULTY_SUCCESS';
export const DELETE_FACULTY_FAILURE = 'DELETE_FACULTY_FAILURE';

//Get 1 Row
export const LOAD_FACULTY = 'LOAD_FACULTY';
export const LOAD_FACULTY_SUCCESS = 'LOAD_FACULTY_SUCCESS';
export const LOAD_FACULTY_FAILURE = 'LOAD_FACULTY_FAILURE';
export const RESET_FACULTY = 'RESET_FACULTY';